// see ADR-0009
pub(crate) mod compile;
pub(crate) mod hashing;
pub mod ports;
pub(crate) mod resolve_knowledge_objects;
pub(crate) mod resolve_object_references;
pub(crate) mod retrieval;
pub mod services;
pub mod views;
