// see ADR-0009
pub(crate) mod artifact_inspection;
pub(crate) mod compile;
pub(crate) mod graph;
pub(crate) mod hashing;
pub(crate) mod patch;
pub(crate) mod resolve_knowledge_objects;
pub(crate) mod resolve_object_references;
pub(crate) mod retrieval;
pub(crate) mod search_artifact;
